server:
  port: 8080

spring:
  application:
    name: myne-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        connect-timeout: 60000
        response-timeout: 60s
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
#      globalcors:
#          cors-configurations:
#            '[/**]':
#              allowed-origins: "*"
#              allowed-methods: "*"
#              allowed-headers: "*"
#              allow-credentials: true        
                   