server:
  port: 8080

spring:
  application:
    name: myne-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        connect-timeout: 60000
        response-timeout: 60s
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
#      globalcors:
#        add-to-simple-url-handler-mapping: true
#        corsConfigurations:
#            '[/**]':
#            allowedOrigins: 
#              - "http://localhost:3000"
#              - "http://localhost:4200"
#              - "https://myne.dbqportal.com"
#              allowed-methods: "*"
#              allowed-headers: "*"
#              allow-credentials: true        
                   